### ISSUE TITLE
Stats page error

### ISSUE THREAD

**Issue by pi0neerpat** [open-dollar/od-app#128]
```
ERROR
maximumFractionDigits value is out of range.
RangeError: maximumFractionDigits value is out of range.
    at new NumberFormat (<anonymous>)
    at formatDataNumber (http://localhost:3001/static/js/bundle.js:33410:10)
    at toPercentage (http://localhost:3001/static/js/bundle.js:34490:80)
    at transformToAnnualRate (http://localhost:3001/static/js/bundle.js:34509:10)
    at http://localhost:3001/static/js/bundle.js:20302:84
    ```

**Comment by pi0neerpat** [comment]
Fixed!
